from .views import *
from django.urls import path

urlpatterns = [
    path('login/', loginuser),
    path('getcustomer/<str:period>/', customer_weekly),
    path('customer/<str:id>/', customer_weekly_details),
    path('getcustomermonthly/', customer_monthly),
    path('customer/monthly/<str:id>/', customer_monthy_details),
    path('incharge/<str:id>/', incharge_details),
    path('incharge1/', incharge),
    path('collection1/', collection),
    path('collection/<str:id>/', collection_details),
    path("collection/save/weekly/", weeklyLoanCollection),
    path("collection/update/weekly/<str:id>/", weeklyLoanCollectionUpdate),
    path("collection/get/weekly/<str:pk>/", customerCollection),
    path("collection/save/montlhy/<str:type>/", monthlyLoanCollection),
    path("collection/update/montlhy/<str:id>/<str:type>/", monthlyLoanCollectionUpdate),
    path("collection/get/monthly/<str:pk>/<str:id>/", customerCollectionmontlhy),
    path("inchargecollection/", InchargeCollection),
    path("inchargecollection/<str:id>/", InchargeCollectionUpdate),
    path('inchargeacc/<str:id>/', getCollectionDetails),
    path('intrestdata/<str:id>/', getIntrest),
    path('intrestdatadetails/<str:id>/', getIntrestDetails),
    path("CIH/", calculateCIH),
    path("close/monthlyloan/", closeLoanMonthly),
    path("active/weeklyloan/", activeWeeklyLoan),
    path("active/montlhyloan/", activeMontlhyLoan),
    path("active/incharge/", activeIncharge),
]