# Generated by Django 4.1.1 on 2023-02-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bak', '0002_remove_customers_incharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('expire', models.DateTimeField()),
                ('login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
