# Generated by Django 4.1.1 on 2023-02-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bak', '0003_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='emd_date',
            new_name='end_date',
        ),
        migrations.AlterField(
            model_name='customers',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='incharge',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlyloans',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
