# Generated by Django 4.1.1 on 2023-02-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bak', '0004_rename_emd_date_customers_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyloans',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
