# Generated by Django 4.1.1 on 2023-02-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bak', '0005_customers_balance_monthlyloans_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountcollection',
            name='account_type',
        ),
        migrations.AddField(
            model_name='amountcollection',
            name='date',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='amountcollection',
            name='collected_by',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
