# Generated by Django 4.1.1 on 2023-02-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bak', '0007_incharge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='incharge',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
