# Generated by Django 4.1.1 on 2023-02-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bak', '0008_incharge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountcollection',
            name='type',
            field=models.CharField(default='weekly', max_length=100),
        ),
    ]
