# Generated by Django 4.1.1 on 2023-02-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bak', '0009_amountcollection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountcollection',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
