# Generated by Django 4.1.1 on 2023-02-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bak', '0011_monthintrestcollection_monthlyloans_intrest_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InchargeAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incharge_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='incharge',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
