# Generated by Django 4.1.1 on 2023-02-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bak', '0012_inchargeacc_incharge_total_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inchargeacc',
            name='incharge_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
