# Generated by Django 4.1.1 on 2023-02-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bak', '0013_alter_inchargeacc_incharge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyloans',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='monthlyloans',
            name='end_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
