# Generated by Django 4.1.1 on 2023-02-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bak', '0014_remove_monthlyloans_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountcollection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incharge',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inchargeacc',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monthintrestcollection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monthlyloans',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
